### ISSUE TITLE
minor comment about installation libglew on ubuntu 24.04

### ISSUE THREAD

**Issue by dbrakenhoff** [ODLS1/Mlaem_Pre-Release#1]
I came across this on Github and decided to give a try just now. It works, so very cool to see MLAEM in action (I hadn't seen it before). Just one small note on installation of libglew on Ubuntu 24.04, i needed to add -dev to get it to work :) : 
```bash
sudo apt install libglew-dev
```

**Comment by estrac** [comment]
Thank you for the kind feedback! We also greatly appreciate your note about requiring the `libglew-dev` library for the GLX-XWindows Linux version (Glew is statically linked for the ELG-Wayland version). The `README.md` file has been updated to reflect this.

**Comment by estrac** [comment]
This issue has been fully resolved by statically linking `Glew` into both Linux executables (the `OpenGL GLX` and `EGL` versions). Documentation in `README.md` has been updated.
